import { Page } from "../../router";
import { PageId } from "../../types";
export declare class ScanPage implements Page {
    id: PageId;
    private element;
    private cameraManager;
    private resultPanel;
    private readonly pwaPromptManager;
    private pwaTimeout?;
    private hasCompletedScanAwaitingClose;
    private viewportWrapper;
    private cameraReader;
    private viewfinderOverlay;
    private floatingControlsLeft;
    private floatingControlsRight;
    private cameraPopover;
    private cameraLoader;
    private permissionArrow;
    private torchBtn;
    private cameraBtn;
    private fitBtn;
    private fileBtn;
    private fallbackUI;
    private dragZone;
    private fileInputHelper;
    private dropOverlay;
    private isCoverMode;
    private isTorchOn;
    private availableCameras;
    private popoverOpen;
    constructor();
    getElement(): HTMLElement;
    onMount(): Promise<void>;
    onUnmount(): Promise<void>;
    private initCameraCallbacks;
    private initResultPanel;
    private showLoader;
    private hideLoader;
    private startScanSequence;
    private updateCameraControlsUI;
    private saveActiveCamera;
    private showFallback;
    private createPageStructure;
    private handleToggleTorch;
    private handleToggleFitMode;
    private handleToggleCameraPopover;
    private openPopover;
    private closePopover;
    private renderCameraPopoverOptions;
    private handleSelectCamera;
    private triggerFileSelect;
    private handleFileSelected;
    private processImageFile;
    private initDragDrop;
}
